extends Node2D

@onready var Guerreiro = preload("res://script/Guerreiro.gd")
@onready var Arqueiro = preload("res://script/arqueiro.gd")
@onready var Mago = preload("res://script/mago.gd")
@onready var Curandeiro = preload("res://script/curandeiro.gd")
@onready var esp = preload("res://script/Espada.gd")
@onready var esc = preload("res://script/Escudo.gd")
@onready var armor = preload("res://script/armor.gd")
@onready var potion = preload("res://script/pocao.gd")
@onready var Leao = preload("res://script/leao.gd")
@onready var Elefante = preload("res://script/elefante.gd")
@onready var Macaco = preload("res://script/macaco.gd")
@onready var Girafa = preload("res://script/girafa.gd")



func _ready() -> void:
	var guerreiromortal = Guerreiro.new(0, 0)
	var arqueiromagico = Arqueiro.new(0, 0)
	var magofire = Mago.new(0, 0)
	var curador = Curandeiro.new(0, 0)
	magofire.lançar_magia(60, 40)
	magofire.nivel_qi(30, 40)
	guerreiromortal.atacar(0)
	guerreiromortal.defender(0)
	arqueiromagico.atirar_flecha(1000)
	arqueiromagico.esquivar("Direita", "Direita")
	curador.curar(50, 20)
	curador.proteger(30, 50)
	var giraff = Girafa.new(2, 6)
	var macc = Macaco.new(5, 7)
	var elefan = Elefante.new(2, 6)
	var leaozin = Leao.new(3, 2)
	leaozin.correr()
	leaozin.rugir()
	elefan.pisar()
	elefan.lembrar()
	macc.balancar()
	macc.comer_banana(2)
	giraff.alcancar_folhas()
	giraff.observar()
